on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.request('PUT /repos/e3c8f1a924/github-actions-test/contents/test.txt', {
              owner: 'e3c8f1a924',
              repo: 'github-actions-test',
              message: 'Update test.txt',
              content: 'success'
            });
