on:
  push:
    branches: [ "main" ]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/index.js');
            await script({ github, context, core });
            await github.request('PUT /repos/e3c8f1a924/github-actions-test/contents/test.txt', {
              owner: 'e3c8f1a924',
              repo: 'github-actions-test',
              message: 'Update test.txt',
              content: 'bXkgbmV3IGZpbGUgY29udGVudHM='
            });
